repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-print,
          flake8-implicit-str-concat,
        ]
  - repo: https://github.com/PyCQA/isort
    rev: master
    hooks:
      - id: isort
        args: ['--check-only', '--filter-files']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: master
    hooks:
      - id: markdownlint
        name: markdownlint-readme
        files: 'README.md'
