name: CI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-sdist:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python v3.8
        with:
          python-version: 3.8
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build-wheel:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python v3.8
        with:
          python-version: 3.8
      - name: Install wheel
        run: python -m pip install --upgrade wheel
      - name: Build wheel
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  pypi-upload:
    name: Upload to PyPI
    needs:
      - build-sdist
      - build-wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
          # repository_url: https://test.pypi.org/legacy/
